from pathlib import Path

import pytest
import yaml

from rehearse.train.cli import TrainConfig, _merge_yaml, _run


@pytest.fixture
def base_yaml(tmp_path):
    cfg = {
        "run_dir": "",
        "max_steps": 100,
        "batch_size": 8,
        "duration_sec": 50.0,
        "lora": {"rank": 64, "enable": True},
    }
    p = tmp_path / "config.yaml"
    p.write_text(yaml.dump(cfg))
    return p


def test_merge_yaml_passthrough(base_yaml):
    """Base YAML values are preserved when no overrides are given."""
    tc = TrainConfig(config=base_yaml, run_dir="runs/test")
    out = _merge_yaml(tc)
    result = yaml.safe_load(Path(out).read_text())
    assert result["max_steps"] == 100
    assert result["batch_size"] == 8
    assert result["lora"]["rank"] == 64


def test_merge_yaml_overrides(base_yaml):
    """Non-zero override fields replace values from the base YAML."""
    tc = TrainConfig(
        config=base_yaml,
        run_dir="runs/test",
        max_steps=500,
        batch_size=4,
        lora_rank=32,
        duration_sec=25.0,
    )
    out = _merge_yaml(tc)
    result = yaml.safe_load(Path(out).read_text())
    assert result["max_steps"] == 500
    assert result["batch_size"] == 4
    assert result["lora"]["rank"] == 32
    assert result["duration_sec"] == 25.0
    assert result["lora"]["enable"] == True  # non-overridden nested keys persist


def test_merge_yaml_zero_does_not_override(base_yaml):
    """Zero values leave the base YAML untouched (zero means no override)."""
    tc = TrainConfig(config=base_yaml, run_dir="runs/test", max_steps=0, batch_size=0)
    out = _merge_yaml(tc)
    result = yaml.safe_load(Path(out).read_text())
    assert result["max_steps"] == 100
    assert result["batch_size"] == 8


def test_merge_yaml_zero_float_does_not_override(base_yaml):
    """Zero float values do not trigger overrides (zero means no override)."""
    tc = TrainConfig(config=base_yaml, run_dir="runs/test", duration_sec=0.0)
    out = _merge_yaml(tc)
    result = yaml.safe_load(Path(out).read_text())
    assert result["duration_sec"] == 50.0


def test_merge_yaml_run_dir_autogenerated(base_yaml):
    """run_dir is auto-generated when TrainConfig.run_dir is empty."""
    tc = TrainConfig(config=base_yaml)  # run_dir defaults to ""
    out = _merge_yaml(tc)
    result = yaml.safe_load(Path(out).read_text())
    assert result["run_dir"].startswith("runs/")
    assert "config" in result["run_dir"]  # contains config stem


def test_merge_yaml_run_dir_explicit(base_yaml):
    """Explicit run_dir is written into the merged YAML."""
    tc = TrainConfig(config=base_yaml, run_dir="runs/my-experiment")
    out = _merge_yaml(tc)
    result = yaml.safe_load(Path(out).read_text())
    assert result["run_dir"] == "runs/my-experiment"


def test_merge_yaml_wandb_key_injected(tmp_path, monkeypatch):
    """WANDB_API_KEY env var is injected into wandb.key when section exists."""
    cfg = {"run_dir": "", "wandb": {"project": "test", "key": ""}}
    p = tmp_path / "config.yaml"
    p.write_text(yaml.dump(cfg))

    monkeypatch.setenv("WANDB_API_KEY", "sk-test-123")
    tc = TrainConfig(config=p, run_dir="runs/test")
    out = _merge_yaml(tc)
    result = yaml.safe_load(Path(out).read_text())
    assert result["wandb"]["key"] == "sk-test-123"


def test_merge_yaml_no_wandb_key_without_section(base_yaml, monkeypatch):
    """WANDB_API_KEY is not injected when YAML has no wandb section."""
    monkeypatch.setenv("WANDB_API_KEY", "sk-test-123")
    tc = TrainConfig(config=base_yaml, run_dir="runs/test")
    out = _merge_yaml(tc)
    result = yaml.safe_load(Path(out).read_text())
    assert "wandb" not in result


def test_merge_yaml_output_is_valid_yaml(base_yaml):
    """Output file is valid YAML."""
    tc = TrainConfig(config=base_yaml, run_dir="runs/test")
    out = _merge_yaml(tc)
    result = yaml.safe_load(Path(out).read_text())
    assert isinstance(result, dict)


def test_run_routes_to_modal_when_flag_true(base_yaml, monkeypatch):
    """_run calls modal.run_training when with_modal=True."""
    called = []
    monkeypatch.setattr("rehearse.train.modal.run_training", lambda d: called.append(d))
    tc = TrainConfig(config=base_yaml, run_dir="runs/test", with_modal=True)
    _run(tc)
    assert len(called) == 1
    assert called[0]["run_dir"] == "runs/test"


def test_run_routes_to_local_when_flag_false(base_yaml, monkeypatch):
    """_run calls subprocess.run when with_modal=False."""
    calls = []
    monkeypatch.setattr("subprocess.run", lambda cmd, **kw: calls.append(cmd))
    tc = TrainConfig(config=base_yaml, run_dir="runs/test", with_modal=False)
    _run(tc)
    assert len(calls) == 1
    assert calls[0][0] == "torchrun"


def test_dry_run_shows_routing_modal(base_yaml, capsys):
    """dry_run prints routing decision for Modal."""
    tc = TrainConfig(config=base_yaml, run_dir="runs/test", with_modal=True, dry_run=True)
    _run(tc)
    out = capsys.readouterr().out
    assert "Modal" in out


def test_dry_run_shows_routing_local(base_yaml, capsys):
    """dry_run prints routing decision for local torchrun."""
    tc = TrainConfig(config=base_yaml, run_dir="runs/test", with_modal=False, dry_run=True)
    _run(tc)
    out = capsys.readouterr().out
    assert "local" in out
