#!/usr/bin/env python3
"""Fetch the local MME-Emotion v0 10-clip subset.

This script downloads the Hugging Face dataset to a local cache, extracts the
ER_Lab archive, copies selected clips into the eval dataset directory, and
rewrites the local manifest from the upstream annotations.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path
from typing import Any

REPO_ID = "Karl28/MME-Emotion"
SUBSET = "ER_Lab"
LABEL_SET = [
    "Anger",
    "Sadness",
    "Surprise",
    "Happiness",
    "Excited",
    "Fear",
    "Frustration",
    "Neutral",
    "Other",
]

DEFAULT_CACHE_DIR = Path(".cache/mme-emotion")
DEFAULT_OUT_DIR = Path("evals/datasets/mme-emotion/v0-10clip")

# Chosen from the HF preview so the scaffold is immediately grounded in real
# annotation ids. "Other" is not represented in the ER_Lab preview rows; use a
# second Frustration example to keep the 10-clip loop useful.
SELECTED_VIDEO_IDS = [
    "ER_Lab/Ses05M_script01_1_F034.mp4",  # Anger
    "ER_Lab/Ses05M_script02_2_F031.mp4",  # Sadness
    "ER_Lab/Ses05M_impro02_F001.mp4",  # Surprise
    "ER_Lab/Ses05M_impro03_M006.mp4",  # Happiness
    "ER_Lab/Ses05F_script03_1_M026.mp4",  # Excited
    "ER_Lab/Ses05F_impro02_F000.mp4",  # Fear
    "ER_Lab/Ses05M_impro04_M006.mp4",  # Frustration
    "ER_Lab/Ses05M_impro05_M005.mp4",  # Neutral
    "ER_Lab/Ses05F_impro08_M015.mp4",  # Frustration
    "ER_Lab/Ses05F_impro01_M015.mp4",  # Frustration
]


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    cache_dir = args.cache_dir
    out_dir = args.out_dir
    clips_dir = out_dir / "clips"

    cache_dir.mkdir(parents=True, exist_ok=True)
    out_dir.mkdir(parents=True, exist_ok=True)
    clips_dir.mkdir(parents=True, exist_ok=True)

    if not args.skip_download:
        _download_dataset(cache_dir)

    annotation_path = _find_one(cache_dir, f"{SUBSET}.json")
    archive_path = _find_one(cache_dir, f"{SUBSET}.zip")
    extracted_root = cache_dir / "extracted"
    _extract_archive(archive_path, extracted_root)

    annotations = _load_annotations(annotation_path)
    rows_by_video_id = {str(row["video_id"]): row for row in annotations}

    manifest_rows: list[dict[str, Any]] = []
    for index, video_id in enumerate(SELECTED_VIDEO_IDS, start=1):
        row = rows_by_video_id.get(video_id)
        if row is None:
            raise SystemExit(f"{video_id} not found in {annotation_path}")

        src = _find_extracted_clip(extracted_root, video_id)
        dst = clips_dir / Path(video_id).name
        shutil.copy2(src, dst)

        manifest_rows.append(
            {
                "id": f"mme-er-lab-{index:03d}",
                "file": f"clips/{dst.name}",
                "label": row["label"],
                "duration_s": row.get("duration_s"),
                "speaker_id": _speaker_id_from_filename(dst.stem),
                "source_id": dst.stem,
                "video_id": video_id,
            }
        )

    manifest = {
        "_meta": {
            "name": "mme-emotion",
            "version": "v0-10clip",
            "source": REPO_ID,
            "subset": SUBSET,
            "note": "Generated by setup/fetch_mme_emotion.py. Media files are gitignored.",
        },
        "subset": SUBSET,
        "audio_max_s": 30,
        "label_set": LABEL_SET,
        "clips": manifest_rows,
    }
    manifest_path = out_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    (clips_dir / ".gitkeep").touch(exist_ok=True)

    print(f"Wrote {manifest_path}")
    print(f"Copied {len(manifest_rows)} clips to {clips_dir}")
    return 0


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--cache-dir",
        type=Path,
        default=DEFAULT_CACHE_DIR,
        help="where to download/extract the full HF dataset",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=DEFAULT_OUT_DIR,
        help="local v0 subset directory",
    )
    parser.add_argument(
        "--skip-download",
        action="store_true",
        help="reuse an existing cache-dir with ER_Lab.json and ER_Lab.zip",
    )
    return parser.parse_args(argv)


def _download_dataset(cache_dir: Path) -> None:
    if shutil.which("hf") is None:
        raise SystemExit(
            "Missing `hf` CLI. Install it with `uv tool install huggingface_hub` "
            "or run inside an environment that already has huggingface_hub."
        )

    cmd = [
        "hf",
        "download",
        REPO_ID,
        "--repo-type",
        "dataset",
        "--local-dir",
        str(cache_dir),
    ]
    subprocess.run(cmd, check=True)


def _find_one(root: Path, filename: str) -> Path:
    matches = list(root.rglob(filename))
    if not matches:
        raise SystemExit(f"Could not find {filename} under {root}")
    return matches[0]


def _extract_archive(archive_path: Path, extracted_root: Path) -> None:
    marker = extracted_root / ".complete"
    if marker.exists():
        return
    if extracted_root.exists():
        shutil.rmtree(extracted_root)
    extracted_root.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(archive_path) as archive:
        archive.extractall(extracted_root)
    marker.touch()


def _load_annotations(path: Path) -> list[dict[str, Any]]:
    data = json.loads(path.read_text())
    if not isinstance(data, list):
        raise SystemExit(f"Expected {path} to contain a JSON list")
    return data


def _find_extracted_clip(extracted_root: Path, video_id: str) -> Path:
    direct = extracted_root / video_id
    if direct.exists():
        return direct

    filename = Path(video_id).name
    matches = list(extracted_root.rglob(filename))
    if not matches:
        raise SystemExit(f"Could not find extracted clip for {video_id}")
    return matches[0]


def _speaker_id_from_filename(stem: str) -> str:
    parts = stem.split("_")
    if len(parts) >= 4:
        return f"{parts[0]}_{parts[-1]}"
    return stem


if __name__ == "__main__":
    sys.exit(main())
